# Generated by Django 3.0.7 on 2020-06-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
