# Generated by Django 3.0.7 on 2020-06-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_api', '0002_auto_20200618_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='content',
            field=models.FileField(upload_to='files/'),
        ),
    ]
